In [17]:
import numpy as np

In [18]:
a = np.random.randn(5)
a

array([-0.34891374,  0.22914796, -0.45849074,  0.37967542, -0.62275993])

In [19]:
print(a.shape)

(5,)


In [20]:
a.T  # It looks the same with the vector a !!!

array([-0.34891374,  0.22914796, -0.45849074,  0.37967542, -0.62275993])

In [21]:
print(np.dot(a,a.T))  # a times a.T cannot be a single number. Don't use rank 1 arrays

0.9164466987376821


In [22]:
# Better way of doing this
a = np.random.randn(5,1) # Define the shape
a

array([[-1.64379507],
       [-1.68009729],
       [-0.11769575],
       [-2.84111272],
       [-1.78331212]])

In [23]:
a.T

array([[-1.64379507, -1.68009729, -0.11769575, -2.84111272, -1.78331212]])

In [26]:
dot_product = np.dot(a,a.T) 
dot_product

array([[2.70206222, 2.76173563, 0.19346769, 4.67020707, 2.93139966],
       [2.76173563, 2.8227269 , 0.19774031, 4.77334577, 2.99613785],
       [0.19346769, 0.19774031, 0.01385229, 0.33438689, 0.20988826],
       [4.67020707, 4.77334577, 0.33438689, 8.07192147, 5.06659074],
       [2.93139966, 2.99613785, 0.20988826, 5.06659074, 3.18020211]])

In [28]:
dot_product.shape == (5,5)

True