# Set up
Note that PyTorch also required a seed since we will be generating random tensors. 

In [2]:
import numpy as np
import torch

In [3]:
SEED = 1234

In [5]:
# Set seed for reproducibility
np.random.seed(seed=SEED)
torch.manual_seed(SEED)

# Basics
Some basics with PyTorch such as creating tensors and converting from common data structures (lists, arrays, etc.) to tensors. 

In [6]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution, (rand(2,3) -> uniform distribution)
print(f"Type: {x.type()}")
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [7]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [8]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
# NumPy array → Tensor
x = torch.Tensor(np.random.rand(2, 3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.1915, 0.6221, 0.4377],
        [0.7854, 0.7800, 0.2726]])


In [10]:
# Changing tensor type
x = torch.Tensor(3, 4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


# Operations
Some basic operations with tensors

In [11]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [12]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 2])
Values: 
tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])


In [13]:
# Transpose
x = torch.randn(2, 3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.8042, -0.1383,  0.3196],
        [-1.0187, -1.3147,  2.5228]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8042, -1.0187],
        [-0.1383, -1.3147],
        [ 0.3196,  2.5228]])


In [14]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [17]:
# Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[0.2111, 0.3372, 0.6638],
        [1.0397, 1.8434, 0.6588]])
Values: 
tensor([1.2508, 2.1805, 1.3226])
Values: 
tensor([1.2120, 3.5418])


# Indexing
How to extract, separate and join values from our tensors

In [21]:
x = torch.randn(3, 4)
print (f"x: \n{x}")
print (f"x[:1]: \n{x[:1]}")
print (f"x[:1, 1:3]: \n{x[:1, 1:3]}")

x: 
tensor([[-0.3449, -1.5447,  0.0685, -1.5104],
        [-1.1706,  0.2259,  1.4696, -1.3284],
        [ 1.9946, -0.8209,  1.0061, -1.0664]])
x[:1]: 
tensor([[-0.3449, -1.5447,  0.0685, -1.5104]])
x[:1, 1:3]: 
tensor([[-1.5447,  0.0685]])


# Slicing

In [61]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print(f"Values: \n{x}")

col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print(f"Values: \n{chosen}")

row_indices = torch.LongTensor([0, 1])
col_indices = torch.LongTensor([0, 2])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1)
print(f"Values: \n{chosen}")

Values: 
tensor([[-0.9505, -0.6567, -1.7232],
        [-0.9854, -0.6118, -0.6743]])
Values: 
tensor([[-0.9505, -1.7232],
        [-0.9854, -0.6743]])
Values: 
tensor([-0.9505, -0.6743])


# Joining

In [36]:
# Concatenation
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print(f"Values: \n{y}")
z = torch.cat([x, x], dim=1) # stack by rows (dim=1 to stack by columns)
print(f"Values: \n{z}")

Values: 
tensor([[-0.4455, -0.4108,  0.3571],
        [-1.4713,  0.9365,  0.2561]])
Values: 
tensor([[-0.4455, -0.4108,  0.3571],
        [-1.4713,  0.9365,  0.2561],
        [-0.4455, -0.4108,  0.3571],
        [-1.4713,  0.9365,  0.2561]])
Values: 
tensor([[-0.4455, -0.4108,  0.3571, -0.4455, -0.4108,  0.3571],
        [-1.4713,  0.9365,  0.2561, -1.4713,  0.9365,  0.2561]])


# Gradients
Let's determine gradients (rate of change) of our tensors with respect to their constituents using gradient bookkeeping. This is useful when we're training our models using backpropagation where we'll use these gradients to optimize our weights with the goals of lowering our objective function (loss).

In [45]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean() # z = sum(y)/N where N = 12 in the example
z.backward() # z has to be scalar
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")

x: 
tensor([[0.7145, 0.5965, 0.0761, 0.1762],
        [0.1008, 0.0073, 0.3606, 0.5587],
        [0.0622, 0.0472, 0.5251, 0.3141]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])
