# Decision Tree Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
df = pd.read_csv('/Users/ozerozdal/Documents/Regression/Data.csv')
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [3]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [4]:
print(X)

[[  41.76 1024.07   73.17]
 [  62.96 1020.04   59.08]
 [  39.4  1012.16   92.14]
 ...
 [  74.33 1012.92   36.48]
 [  69.45 1013.86   62.39]
 [  62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Decision Tree Regression model on the Training set

In [7]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting the Test set results

In [8]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[432.84 431.23]
 [458.53 460.01]
 [466.75 461.14]
 ...
 [471.43 473.26]
 [439.5  438.  ]
 [461.7  463.28]]


## Evaluating the Model Performance

In [9]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, median_absolute_error, explained_variance_score, r2_score

print("Mean absolute error =", round(mean_absolute_error(y_test, y_pred), 4)) 
print("Mean squared error =", round(mean_squared_error(y_test, y_pred), 4)) 
print("Median absolute error =", round(median_absolute_error(y_test, y_pred), 4)) 
print("Explain variance score =", round(explained_variance_score(y_test, y_pred), 4)) 
print("R2 score =", round(r2_score(y_test, y_pred), 4))

Mean absolute error = 3.6984
Mean squared error = 35.3128
Median absolute error = 2.22
Explain variance score = 0.8793
R2 score = 0.8793
